cc_test(
    name = "interpolation-tests",
    srcs = ["interpolation_tests.cpp"],
    defines = ["CATCH_CONFIG_MAIN"],
    deps = [
        "@catch2",
        "@glm//:lib",
        "//interpolation"
    ],
)