load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "interpolation",
    srcs = ["interpolation.cpp"],
    hdrs = ["interpolation.h"],
    deps = [
        "@glm//:lib",
    ],
    visibility = ["//visibility:public"],
)
