load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "utils",
    srcs = [
        "utils.cpp",
        "utils.h",

    ],   
    deps = [
        "//third_party/glad",
    ],
       visibility = ["//visibility:public"],
)
